### ISSUE TITLE
Cookie message

### ISSUE THREAD

**Issue by slaffcheff** [slaffcheff/cliarmy#3]
Follow the internet modern stuff. Must have.

**Comment by slaffcheff** [comment]
Cookie message added at the bottom of the website.

**Comment by teddy931130** [comment]
http://cliarmy.slaffcheff.com/ --> shows cookie message;
http://slaffcheff.com/cliarmy/ ---> doesn't show cookie message;

Just found this out accidentally. Hm... weird    ¯\__(ツ)__/¯

**Comment by slaffcheff** [comment]
Yes, i made it that way.
