### ISSUE TITLE
Gadgets

### ISSUE THREAD

**Issue by slaffcheff** [slaffcheff/cliarmy#7]
Date, time, weather, etc.

**Comment by teddy931130** [comment]
Added Calendar widget, weather RSS feed, and TechCrunch RSS in the footer

**Comment by slaffcheff** [comment]
Good job. Can we make the font smaller? Not only on the gadgets but on the whole foorter?

**Comment by teddy931130** [comment]
Sure thing. Looking into it now.

**Comment by teddy931130** [comment]
Done.
